version: "3.9"
services:
  jupyter:
    image: jupyter/minimal-notebook:python-3.9.6
    ports:
      - "127.0.0.1:8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - .:/home/jovyan/jupyter_env


